### ISSUE TITLE
FFMetrics does not start up reliably and when it does the start button is greyed out

### ISSUE THREAD

**Issue by efassbender** [fifonik/FFMetrics#131]
Hey everyone, I use FFMetrics every now and then to test the quality of an encode and up until today it has been working fine. When I tried to start it today, it just wouldn't start. The Windows 10 Reliability Monitor reported it as "Stopped Working" even though it didn't even (visually) start up. Upon restarting the PC and a couple more tries, it eventually started and I selected the two files, however, now the start button is unavailable. I have downloaded a new instance of v1.3.1 (same one as before) and ffmpeg.exe is in the application's folder. Does anyone have an idea what may be causing this issue?

**Comment by fifonik** [comment]
Please use the latest version 1.4.9b1

**Comment by efassbender** [comment]
@fifonik thanks. I get the same result with the latest beta, however, I think I figured out the cause of this - I was using a reference video that was encoded with Cineform. Does FFMetric support this codec?

**Comment by fifonik** [comment]
FFMetrics is just a frontend, it is up to FFMpeg to support all these formats.
I've just calculated uncompressed vs cineform and do not have the issue:
![image](https://github.com/fifonik/FFMetrics/assets/7234987/4ca264c7-47e9-4af2-b657-e682b435532b)

**Comment by fifonik** [comment]
You can try troubleshooting [steps](https://github.com/fifonik/FFMetrics#troubleshooting).

**Comment by fifonik** [comment]
BTW, I do remember similar issues were caused by too small timeout for FFMpeg calls.

In this case you can try:
- Use shared version of FFMpeg (exe + dlls) as it is usually starts slightly faster;
- Double check that FFMpeg (**not** FFMetrics) is excluded from Anti Virus checks. AV can slow down the large ffmpeg executable quite a lot and it is called by FFMetrics many time;
- Create FFMetrics.conf and increase timesouts (see FFMetrics.conf.example).

**Comment by efassbender** [comment]
Thanks for your help. It seems like I am having some other issues with the PC that I need to address before I can investigate this further. Talk soon!
