### ISSUE TITLE
App fails on h.265 lossless videos

### ISSUE THREAD

**Issue by lashchev** [fifonik/FFMetrics#22]
I converted several 4K videos with HandBrake v1.3.3, x.265 --lossless.
When I load them in the app - Media info stays as N/A.
If I start a project analysis with such videos - PSNR, SSIM, and VMAF won't calculate: progress bar will keep rotating in the related cell in the file list, but project analysis will stop (Button Start appears instead of Stop)

**Comment by fifonik** [comment]
It is strange that FFMetrics allowed you to start analysis without media info. 
It should not.
I will try to re-produce the issue with HandBrake/x265 source.

**Comment by fifonik** [comment]
Could you advise, how you was able to encode in x265 **lossless** with HandBrake 1.3.3?

**Comment by lashchev** [comment]
You can add `lossless=1` to the "Vidoe\Advanced options" section or use command line [like this](https://trac.ffmpeg.org/wiki/Encode/H.265#Losslessencoding)

**Comment by fifonik** [comment]
Oh, I missed you reply, sorry.
Will try re-produce the issue with 0.9.4b later today.

**Comment by fifonik** [comment]
I still could not re-produce the issue in FFMetrics 0.9.6b with videos encoded in Handbrake 1.3.3 using x264/x265 lossless.
It is possible that the issue was already fixed.
Could you double check if you still have it please?

![image](https://user-images.githubusercontent.com/7234987/116994530-2ec0aa00-ad1c-11eb-83e8-29a7dbe893f1.png)
![image](https://user-images.githubusercontent.com/7234987/116994552-341df480-ad1c-11eb-9d90-ba1822dea689.png)
![image](https://user-images.githubusercontent.com/7234987/116994570-397b3f00-ad1c-11eb-86ba-010d80b0fe9f.png)
