### ISSUE TITLE
List of files limited to 12 items

### ISSUE THREAD

**Issue by matthiasduyck** [fifonik/FFMetrics#3]
The list of files seems to be limited to about 12 files. Additionally, the list box cannot be expanded in height.
![image](https://user-images.githubusercontent.com/10989584/93521029-b4c7e600-f92f-11ea-8ea3-ff1c326f397c.png)

**Comment by fifonik** [comment]
As per current 'features' of the app, 12 is the current limitation.
The main reason -- it is impossible to see what is going on on the plot when too many lines are there.
I decided to keep it as is until I separate the plot from main program's window and so the plot will be fully resizable.

**Comment by matthiasduyck** [comment]
> As per current 'features' of the app, 12 is the current limitation.
> The main reason -- it is impossible to see what is going on on the plot when too many lines are there.
> I decided to keep it as is until I separate the plot from main program's window and so the plot will be fully resizable.

Ok, yeah that makes sense indeed. This was also one of the main limitations I ran into when using the application. Although I like the possibility to see the graphs, the become almost impossible to read with a lot of files. Also, when exporting as images, the 'resolution' is the same as in the program, making it just as hard to read. Indeed, having it in a separate window, perhaps with more fine scale/scroll/... controls and perhaps also the ability to toggle individual graphs would be nice. If possible also an export to a csv data file of the full graphs.

**Comment by lashchev** [comment]
Great tool. The one I was looking for! But the limitation of 12 files is quite annoying. I do not use the graph at all and really wanted to compare the results of various codecs and codec options.
I have about 100+ files that were produced by transcoding h.264 into h.265 and I want to compare them with the original by using VMAF primarily.
Ideally, I would add all of them to the project and let it run for a while and later look into the metrics.
If the graph is a problem - you can show the first N files on the graph or (my preference) add a check-box to the list where people can select what file to show. If somebody wants to show 50 files - it is their choice).

**Comment by fifonik** [comment]
If you only need single value per file -- you should create a simple bat file that will do the trick.
Graphs is the main and vital feature of the program (from my point of view).

**Comment by ShortyCM** [comment]
> If you only need single value per file -- you should create a simple bat file that will do the trick.
> Graphs is the main and vital feature of the program (from my point of view).

Well, the convenience of being able to add and remove files from the list of files to be processed is the main draw for me.  I don't care about the graphs, really.  And I don't want to have to go to the trouble of creating batch files every time I want to process a bunch of files, either.  You already have a checkmark system that adds/removes particular files from the graph.  Having 150 files in the project shouldn't be a concern when it comes to the graphs if you are able to simply select the five you are interested in seeing graphed, no?  Your tool is extremely useful, but this 12-file limitation does limit its usefulness.  I'm currently trying to get data on 60 different files, and the 12-file limitation means I am going to have to come back to the computer and babysit it five times to get all the files processed.  Would I want 60 lines on the graph if I were interested in the graph?  Probably not.  Good thing there are checkmarks I can mark or remove in order to tailor the graph when digging through all that data.  Bad thing that I can't process all my files at once and come back to them all having finished processing, though.  You have an extremely good point about not wanting the graphs to be too cluttered.  But you've already built the solution to that problem with the checkmark system.  I hope you'll reconsider and allow us to use more than 12 files at once.  This might be a simple change for a programmer to make, but not everybody is a programmer.  If there were no limit you would still be free to only select 12 files if you only wanted to select 12 files.  If there were no limit I would be able to select as many as I want, so we would both win.

**Comment by fifonik** [comment]
I've just published version 1.1.0 beta 1 that can process more than 12 files in one go.
