### ISSUE TITLE
Freezes on reference input

### ISSUE THREAD

**Issue by RobtCSimon** [fifonik/FFMetrics#4]
Hello,
Is there a file size limit? Any time I try to add a reference file it freezes.
I've tried a whole assortment without any luck.

Thank you!

**Comment by fifonik** [comment]
The program is not analyzing full file. 
For getting media info It is issuing command:
`ffmpeg -hide_banner -i path\to\ref.mp4 -vframes 1 -t 1 -f null -`
The issue with freeezing program was already reported in Vegas forum, however no media with the issue was provided and I'm unable to re-produce the issue.
I have already implemented more verbose loggin in -log-level=debug mode and sent such executable to original reporter. However, I have not heard anything back yet.

Please, let me know If you can send me a file that causing the issue or willing to try the newer executable.

**Comment by fifonik** [comment]
Good news: I tried to add a number of video files I have on my PC as ref into the program and was able to re-produce the issue with some of them.

You can try this executable:
https://www.dropbox.com/s/abfaaeuwll4mbbs/FFMetrics.zip?dl=1

Please let me know if the issue is fixed.

**Comment by RobtCSimon** [comment]
Hey thanks for the quick response and fix!
Works perfectly now!
Thanks so much. This GUI is exactly what I was looking for. I kept getting lost trying to use VMAF in the command line.
Great work.

**Comment by fifonik** [comment]
Thanks for checking. I've published version 0.8.3b with the fix.
