### ISSUE TITLE
New FFmpeg custom compiles not detected by FFmetrics?

### ISSUE THREAD

**Issue by ls-milkyway** [fifonik/FFMetrics#80]
Hi I am using a compiled non-free version of ffmpeg with libvmaf enabled ....but FFmetrics refuses to detect the built ffmpeg with vmaf (only psnr+ssim are available)....what could be the reason? ..I wish to use only my custom compiled FFmpeg. I have some idea, FYI:

1) Compiled FFmpeg is running flawlessly in windows cmd with vmaf:

`ffmpeg -i output.mkv -i ready.mkv -filter_complex "[0:v]scale=3840:1608:flags=bicubic[main];[main][1:v]libvmaf=model=path=vmaf_v0.6.1.json:log_path=VMAF_out.json:n_threads=2:log_fmt=json" -f null -`

2) Vmaf is now using built in models  [check here](https://trac.ffmpeg.org/ticket/9094) ...in json format hence this may be an issue...

3) I am using switches `-Denable_float=true -Denable_tests=false -Denable_docs=false --buildtype=release --default-library=static -Dbuilt_in_models=true` for compiling from git master........any modifications needed here to make it compatible to FFmetrics.

Plz suggest.

**Comment by fifonik** [comment]
I noticed that a new format is used in the most recent ffmpeg manual (model + path instead of model_path). .
Unfortunately, I have not had chance to try such versions yet, so unable to suggest anything.

You can ask ffmetrics to save ffpmeg commands into log, run it with -log-level=debug as suggested on main page and investigate log.

1. I see you are trying to use new format. You have to try if old format still works fine. When logging enabled, you should see all ffmpeg commants that ffmetrics issuing in log.
2. If you do not currently have external vmaf models in vmaf-models folder, ffmetrics feature detection will not even check if vmaf is supported by the ffmpeg.
3. I never compiled ffmpeg by myself so cannot suggest anything.

**Comment by ls-milkyway** [comment]
There are only few repos on github whose authors are really helpful & sincere in their replies...rest all try to escape the real questions or are not at all bothered about providing feasible, working,.. solutions....great work ...keep it up!
