### ISSUE TITLE
Feature Request: MS-SSIM

### ISSUE THREAD

**Issue by ls-milkyway** [fifonik/FFMetrics#89]
[MS-SSIM is better evaluation than SSIM](https://videoclarity.com/PDF/Advancing-To-Multi-Scale-SSIM-Final.pdf) hence please include it in FFmetrics, It is available in ffmpeg as `ffmpeg -i distorted.mpg -i reference.mpg -lavfi libvmaf='feature=name=ms_ssim' -f null -`

You can keep PSNR; SSIM; MS-SSIM & VMAF OR I guess PSNR; MS-SSIM; VMAF because MS-SSIM is greater form of a SSIM type video quality evaluation...thanks.

**Comment by fifonik** [comment]
I'd say I do not like the libvmaf implementation at all.
They've already changed their API a few times over relatively short period of time and do not have some very basic features (for example: feature detection and output to stdout). 
So at this stage I do not have plans to support MS-SSIM through libvmaf. May be later. Sorry.

P.S. if the MS-SSIM output format is the same, one may re-define "Filter" in FFMetrics.conf and calculate MS-SSIM instead of VMAF.

**Comment by ls-milkyway** [comment]
> I'd say I do not like the libvmaf implementation at all.
They've already changed their API a few times over relatively short period of time and do not have some very basic features (for example: feature detection and output to stdout).

Yep, I understand .......even I have faced huge problems in maintaining some projects...specially when their json input structure was changed by the third party API without notice ...literally made  my life ..hell...
